### ISSUE TITLE
Team 15 Phase 2 Winning throws exceptions

### ISSUE THREAD

**Issue by bmatthew123** [cs340tabyu/CatanBugTracker#220]
When a player reaches 10 victory points they should win, however, an exception is thrown that causes the GUI to freeze up. This can be replicated by gaining 9 victory points, and then performing an action (I placed a settlement) that would cause a tenth victory point. The settlement did not get placed and the GUI locked up due a JSON deserializing error.

**Comment by mwilliammyers** [comment]
I got the same issue. Here is the stack trace when it happens for your perusal :smile:: 

```
Exception in thread "AWT-EventQueue-0" com.google.gson.JsonParseException: shared.exception.OutOfRangeException
    at game.client.model.WinnerDeserializer.deserialize(WinnerDeserializer.java:22)
    at game.client.model.WinnerDeserializer.deserialize(WinnerDeserializer.java:12)
    at com.google.gson.TreeTypeAdapter.read(TreeTypeAdapter.java:58)
    at com.google.gson.Gson.fromJson(Gson.java:803)
    at com.google.gson.Gson.fromJson(Gson.java:868)
    at com.google.gson.Gson.fromJson(Gson.java:841)
    at game.client.model.CatanGameModelDeserializer.deserialize(CatanGameModelDeserializer.java:80)
    at game.client.model.CatanGameModelDeserializer.deserialize(CatanGameModelDeserializer.java:23)
    at com.google.gson.TreeTypeAdapter.read(TreeTypeAdapter.java:58)
    at com.google.gson.Gson.fromJson(Gson.java:803)
    at com.google.gson.Gson.fromJson(Gson.java:768)
    at com.google.gson.Gson.fromJson(Gson.java:717)
    at com.google.gson.Gson.fromJson(Gson.java:689)
    at game.client.model.Translator.deserialize(Translator.java:28)
    at game.client.ClientFacade.updateModel(ClientFacade.java:275)
    at game.client.ClientFacade.buildSettlement(ClientFacade.java:241)
    at client.master.MasterController.buildSettlement(MasterController.java:360)
    at client.map.state.PlaceSettlementState.placeSettlement(PlaceSettlementState.java:26)
    at client.map.MapController.placeSettlement(MapController.java:92)
    at client.map.MapView$1.placeSettlement(MapView.java:168)
    at client.map.MapComponent$2.mouseClicked(MapComponent.java:628)
    at java.awt.Component.processMouseEvent(Component.java:6538)
    at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
    at java.awt.Component.processEvent(Component.java:6300)
    at java.awt.Container.processEvent(Container.java:2236)
    at java.awt.Component.dispatchEventImpl(Component.java:4891)
    at java.awt.Container.dispatchEventImpl(Container.java:2294)
    at java.awt.Component.dispatchEvent(Component.java:4713)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
    at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4534)
    at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
    at java.awt.Container.dispatchEventImpl(Container.java:2280)
    at java.awt.Window.dispatchEventImpl(Window.java:2750)
    at java.awt.Component.dispatchEvent(Component.java:4713)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
    at java.awt.EventQueue$4.run(EventQueue.java:731)
    at java.awt.EventQueue$4.run(EventQueue.java:729)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: shared.exception.OutOfRangeException
    at game.client.model.Winner.<init>(Winner.java:36)
    at game.client.model.WinnerDeserializer.deserialize(WinnerDeserializer.java:19)
    ... 51 more
```

**Comment by trialofelements** [comment]
Yeah...this is a Swagger UI error, as it clearly states that the model will return "winner" : "index" and not "winner" : "user". If the TA's could take this into account when considering this for our number of bugs, that would be great.

**Comment by cs340tabyu** [comment]
Fixed but does not return to the game hub, it just closes the program.
