### ISSUE TITLE
Team 18 Phase 2 - Unable to perform maritime trade

### ISSUE THREAD

**Issue by colingm** [cs340tabyu/CatanBugTracker#61]
Steps:
- Have 4 cards of any kind
- Click the button to start a maritime trade

Result:
- The resource is not enabled and you are not able to perform a trade. It doesn't matter if you are on a port of any kind or you just want to trade for 4, nothing ever happens

Expected Result:
- The trade overlay will enable the resources you can trade from having 4 cards or by being on ports and having the right amount of cards and allow you to trade

![image](https://cloud.githubusercontent.com/assets/11670266/10778109/f927918e-7ce7-11e5-80bb-9fa502713fe6.png)

Client Stack Trace:
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
        at client.maritime.MaritimeTradeOverlay.showGiveOptions(MaritimeTradeOve
rlay.java:248)
        at client.maritime.MaritimeTradeController.startTrade(MaritimeTradeContr
oller.java:40)
        at client.maritime.MaritimeTradeView$1.actionPerformed(MaritimeTradeView
.java:47)
        at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
        at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
        at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
        at javax.swing.DefaultButtonModel.setPressed(Unknown Source)

**Comment by austindh** [comment]
Maritime trade is now working. Close issue.
